layout_spectrum: 0.16400255085430154
typography_spectrum: 0.6958969413944621
color:
  brandColors:
    - '#221D17'
    - '#FEFFEF'
    - '#B28C67'
    - '#F4C287'
    - '#5D4835'
  brandStrength: 0.012954187701539239
  lightness: 0.3960236516666811
  saturation: 0.49358110981172704
  rhythmicContrast: 0.32775442962156665
content_rating:
  adult: false
github: true
opengraph:
  type: article
  appId: '1242489762440789'
analytics:
  facebook: ''
  google: UA-54874277-3
  twitter: ''
author:
  name: Charles Pence
  email: cpence@charlespence.com
name: CharlesPence.com
navigation:
  - name: Career Portal
    url: 'http://career.charlespence.com'
    type: external
  - name: Fanboat Studios - Game Development Blog
    url: 'http://games.charlespence.com'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/28a7e37b-6460-4b96-85f0-c6178eca7666.svg
title: Charles Pence
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/c714ad5d-b23a-4f23-b0ca-b817aee59449.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/c714ad5d-b23a-4f23-b0ca-b817aee59449.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: life from my view
purpose: []
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7311ca61-5e70-424d-b044-e4dce540865b.svg
